---

- hosts: openldap
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - local_action: wait_for port=22 host={{ ansible_ssh_host }} search_regex=OpenSSH delay=10

#install openldar server on the ldap machines
- hosts: openldap 
  remote_user: root
  roles:
#    - install_openldap
    - install_phpldapadmin