---
- hosts: rancher-servers
  roles:
    - docker
  vars:
    version: 1.0
  remote_user: vagrant
  become: yes
  become_user: root
  tasks:
    - name: run rancher server container
      docker: 
        name: rancher_server
        image: registry.cecdat.com:5000/rancher/server
        ports: 
          - "8080:8080"
        restart_policy: always
